### ISSUE TITLE
Tile Blocks

### ISSUE THREAD

**Issue by reynoldtan** [TripalCultivate/TripalCultivate-Theme#10]
![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/d6032d87-77f9-4963-b383-32f4f81756de)

This si the mockup of the large half tile in the tiles section. Each entry added to this tile will go into a stack that the frontend will sort by date field (show the latest as default) and layout entry metadata as shown in the mockup. User can view each item in the stack by using the controls provided.

Backend:
**Section** is a select field that lets user tag an entry as a news and updates or an upcoming events. This tag will be shown in the title area to indicate the type of entry. 

**Title** is a one full sentence making up the title text of the entry.

**Link** can either be an internal page or external url (open a new tab/window when clicked).

**Cover** image is an image relating to the entry and must occupy the entire height and width of the tile.

**Date** auto-generated value used for sorting the entries

Example:
![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/7fd8d609-7d02-4441-9cb3-cb42e94b6de3)

**Comment by reynoldtan** [comment]
![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/0f47161b-f77f-4975-ad48-bf1c69ff4d22)

This is the mockup of banner style tile. Entry to this tile can displayed tall (portrait) or wide (landscape) in the frontend. Cover image covers half the width of the tile allowing custom color to fill the other half.

Backend:

**Title** is a one full sentence making up the title text of the entry.

**Link** can either be an internal page or external url (open a new tab/window when clicked).

**Cover** image is an image relating to the entry and must occupy the entire height and width of the tile.

**Background color** a hex color value


NOTE: What happens when multiple of this tiles are added? cycle through?

Example:
![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/aadaaf36-f6d9-407a-8a80-1592726391ca)

**Comment by reynoldtan** [comment]
![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/66c25408-7d3d-45d1-91b3-1fe252cffcdd)

This is the mockup for standard tile showing a custom link to a page/article with a relevant icon image.

Backend

**Link title** the title of the link that will appear in the tile.

**Link** can either be an internal page or external url (open a new tab/window when clicked).

**Icon** image to graphically describe the link.

**Background color** a hex color value

Examples:

![image](https://github.com/TripalCultivate/TripalCultivate-Theme/assets/15472253/d439fc5d-2393-4d74-8004-7e1fddfad2c1)

**Comment by reynoldtan** [comment]
Block implementation:
Create/add additional configuration variable to hold value for the following:

**large half tile**
  - section
  - title
  - link
  - cover
  - date

**banner style tile**
  - orientation
  - title
  - link
  - cover
  - bgcolor

**standard tile**
  - title
  - link
  - icon
  - bgcolor
  

Schema definitions
```
large_half_tile: 
  type: mapping
  label: 'Large Half TIle - news, updates, and events'
  mapping:
    section: 
      type: string
      label: 'Section: News and Updates or Upcoming Events'
    title:
      type: string
      label: 'Title'
    link:
      type: string
      label: 'Target page link'
    cover:
      type: uri
      label: 'Conver image of the tile title'
    date: 
      type: string
      label: 'Entry date created'

```
